### ISSUE TITLE
weird `slate.status` phenomenon

### ISSUE THREAD

**Issue by kangarang** [ConsenSys/panvala#84]
some context: i've completed the lifecycle of an epoch (epochNumber: 1), during which i created 2 slates with 2 different accounts, staked on them with the respective slate-creator account, voted for slate 0 using a delegate (30 million tokens), and voted for slate 1 using the tokenHolder account (20 million tokens). then i revealed the ballots and tallied the votes using scripts. there was obviously some time-traveling involved as well.

i am now in epochNumber 2, and for some strange reason, slate 0 has a status of `Accepted` while slate 1 is still `Staked`:

<img width="728" alt="ss- 2019-06-21 at 11 58 44 AM" src="https://user-images.githubusercontent.com/18040654/59935513-f8c1f780-941b-11e9-9634-4f2e2d5bcfcf.png">

here is the in-browser console output of each slate:

<img width="869" alt="ss- 2019-06-21 at 11 59 55 AM" src="https://user-images.githubusercontent.com/18040654/59935603-24dd7880-941c-11e9-98f4-9caf9844836b.png">

here are all the events that occurred:

<img width="267" alt="ss- 2019-06-21 at 12 01 49 PM" src="https://user-images.githubusercontent.com/18040654/59935698-6110d900-941c-11e9-9caa-03df9f596aab.png">

seeing as the `ConfidenceVoteFinalized` event was emitted, my mind is boggled because just prior to that, the contract calls [`rejectLosingSlates`](https://github.com/ConsenSys/panvala/blob/develop/governance-contracts/contracts/Gatekeeper.sol#L704) which should [in theory change the status of every non-confidence-vote-winning slate](https://github.com/ConsenSys/panvala/blob/develop/governance-contracts/contracts/Gatekeeper.sol#L851)

wat do?

**Comment by niran** [comment]
It looks like the `Contest` structures are created implicitly in `stakeTokens()`, which pushes the slate onto the `stakedTokens` array. I can't find any code that pushes slates onto the `slates` array, but `slates` is used by `contestSlates()` in the two functions that reject losers.

**Comment by kangarang** [comment]
this is correct. what is returned by `contestSlates` is always an empty array `contest.slates` because the slates actually exist on the array `contest.stakedSlates`

tests relying on `contestSlates`:

https://github.com/ConsenSys/panvala/blob/develop/governance-contracts/test/gatekeeper.js#L2411

https://github.com/ConsenSys/panvala/blob/develop/governance-contracts/test/gatekeeper.js#L3064

https://github.com/ConsenSys/panvala/blob/develop/governance-contracts/test/gatekeeper.js#L3877

https://github.com/ConsenSys/panvala/blob/develop/governance-contracts/test/gatekeeper.js#L3939

**Comment by akuanti** [comment]
Initially, `slates` contained all the slates in the contest. Then, when I added the staking, I used `stakedSlates` to store the IDs of slates that determine the contest's status. In my head, unstaked slates are not *really* part of the contest, despite being part of the struct, since you can't vote on them. Therefore, it doesn't make sense to reject them explicitly. I also think this makes sense because part of the purpose of staking is to avoid spam, and I would prefer not to spend gas operating on slates that no one has bothered to stake on.

That being said, I did forget to push onto the `slates` array, so since `slates` is unused, we should either update to put all the slates in it (`contestSlates()` is more accurately thought of as `resourceSlates()`), or delete the variable completely. Also, I think that if the contest has status `Finalized`, the frontend should display any unstaked slates as rejected.

**Comment by kangarang** [comment]
solved: #97
